#!/bin/bash

cd "./TESTING"

[[ ! -e "${PWD}/0" ]] && echo "No files" && exit 0

y=0
while [[ $y -lt 10 ]]; do
	cd "$y"

	while read -r FILE; do
		rm "${FILE}"
	done < <(find . -type f -name '*')

	cd "../"
	y=$(( $y + 1 ))
done

cd "../"
